FROM php:8.4.4-apache

RUN apt-get update && apt-get install -y \
unzip \
libzip-dev \
libpng-dev \
&& docker-php-ext-install pdo pdo_mysql gd zip \
&& a2enmod rewrite

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY . /var/www/html

WORKDIR /var/www/html

COPY php.dev.ini /usr/local/etc/php/php.ini

RUN composer install --no-dev --optimize-autoloader --working-dir=/var/www/html

EXPOSE 80

CMD ["apache2-foreground"]

